/**
 * Snapshot loaders for register replay output.
 *
 * Reads from /data/snapshots/{slug}/ generated by
 * service-publications-docs/scripts/generate_register_snapshots.rb.
 */
import { readFileSync, existsSync, readdirSync } from "node:fs";
import { join } from "node:path";

// Use process.cwd() rather than import.meta.url so the path is
// stable across Astro SSR build contexts.
const SNAPSHOT_ROOT = join(process.cwd(), "data", "snapshots");

export interface RegisterEntry {
  [key: string]: unknown;
}

export interface ChangeHistoryEntry {
  type: "ADD" | "SUP" | "REP" | "LIR" | "MOD" | "DEL" | "SEED";
  ob_issue: number | null;
  identifier: Record<string, unknown>;
}

export interface RegisterState {
  slug: string;
  at_ob_issue: number | null;
  entry_count: number;
  lapsed_count: number;
  deleted_count: number;
  error_count: number;
  errors?: string[];
  active_entries: RegisterEntry[];
  lapsed_keys: string[];
  lapse_reasons?: Record<string, unknown>;
  deleted_keys: string[];
  history: ChangeHistoryEntry[];
}

export interface RegisterManifest {
  slug: string;
  register_id: string;
  recommendation?: string;
  title: { en?: string; fr?: string; es?: string };
  key_field: string;
  seed_issue: number | null;
  touched_issues: number[];
}

// SNAPSHOT_ROOT is defined above.

function readJson<T>(path: string): T | null {
  if (!existsSync(path)) return null;
  try {
    return JSON.parse(readFileSync(path, "utf-8")) as T;
  } catch {
    return null;
  }
}

export function listSnapshotSlugs(): string[] {
  if (!existsSync(SNAPSHOT_ROOT)) return [];
  return readdirSync(SNAPSHOT_ROOT).filter((name) => {
    const path = join(SNAPSHOT_ROOT, name);
    return existsSync(join(path, "manifest.json"));
  });
}

export function loadManifest(slug: string): RegisterManifest | null {
  return readJson<RegisterManifest>(join(SNAPSHOT_ROOT, slug, "manifest.json"));
}

export function loadCurrentState(slug: string): RegisterState | null {
  return readJson<RegisterState>(join(SNAPSHOT_ROOT, slug, "current.json"));
}

export function loadStateAtIssue(slug: string, obIssue: number): RegisterState | null {
  return readJson<RegisterState>(
    join(SNAPSHOT_ROOT, slug, `at-${obIssue}.json`),
  );
}

/**
 * Group the entries of `state.history` by `ob_issue`, returning a map
 * keyed by issue number whose value is the list of (type, code) pairs
 * applied at that issue. Used by the recommendation page to inline
 * the changed-entry codes per amendment without loading full entry
 * data.
 */
export function groupHistoryByIssue(
  state: RegisterState,
): Map<number, ChangeHistoryEntry[]> {
  const out = new Map<number, ChangeHistoryEntry[]>();
  for (const entry of state.history) {
    if (entry.ob_issue === null) continue;
    const arr = out.get(entry.ob_issue) ?? [];
    arr.push(entry);
    out.set(entry.ob_issue, arr);
  }
  return out;
}
