source "https://rubygems.org"

gem "jekyll", "~> 4.2"

gem "nokogiri"

group :jekyll_plugins do
  gem "jekyll-plugin-frontend-build"

  # TODO: The feed generated by default is empty. To enable the feed,
  # further plugin configuration may be needed.
  # gem "jekyll-feed", "~> 0.6"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.0" if Gem.win_platform?

# Converts AsciiDoc-formatted contents of NNP communications
gem "asciidoctor"

gem "relaton"
