Generates a web-based representation of individual OB issues
and amendment search across OB issues.

= Authoring

See link:https://github.com/riboseinc/itu-ob-data/[itu-ob-data]
for an example (work in progress).

== Referenced publications

Many messages in OB issue amend previous publications.

To avoid repeating publication titles and other metadata,
each publication is given an ID.

When a publication is annexed to an OB issue,
and whenever it is amended in subsequent issues,
its publication ID is referenced.

Place all publications under `_lists/{{ List ID }}/`.
(There is assumed to be one type of publication as of now, called List.)

All Lists must specify a “position” when annexed to an OB issue.
Amendments to such lists should specify the position being amended as well.
(Technically this is redundant,
as we can infer the position being amended by finding which
position of the list was annexed to OB last,
but currently it is used for data consistenty check.)

Publications that are not annexed (e.g., “external” List V),
but are amended, should also be included under `_lists/`.
For them amendments are not required to specify position, but should specify
whatever issue/version of the list being amended, depending on the list
(currently not normalized).

== OB issues

Place each OB issue under `_issues/{{ OB No. }}/` directory.

Each OB issue should contain the following files:

* `meta.yaml` — Information about OB issue: number, date, authors, etc.
* `general.yaml` — General information from the OB issue.
* `amendments.yaml` — The amendments part from the OB issue.
* `annexes.yaml` — Any annexes to this OB issue.
* `nnp_communications/{{ filename }}` — Texts of communications mentioned
  in the General Information part under E.164 section.
  The filename is referenced under `_contents` key for each communication
  in `general.yaml`.

== NNP data (WIP)

NNP-related data, and changes to that data, is not described formally
in OB issues. Place NNP data in XML, obtained from NNP team, under `nnp/`.

= Implementation details

The following plugins enable the site to function:

* Issue data reader — processes OB issue YAML, AsciiDoc and NNP XML as needed,
  and populates ``site.data`` with structured information
  about OB issues and changes in telecommunications landscape covered by ITU
* Issue page generator — creates a page for each OB issue using ``site.data``
* Amendment search index generator — to facilitate client-side search
  of changes in ITU, creates JSON indexes from OB issue data and from NNP data
* Localizer — implements two template tags.
** Template tag `{% trans a_string %}` allows to translate string variables specified
   in the form of { <lang1>: <string1>, <lang2>: <string2> }.
** Template tag `{% trans_file a_filename %}` includes file, specified by name relative
   to current issue root, using language-specific version (<lang>-<a_filename>) if available.
   It also parses AsciiDoc into HTML, so it does not belong under localizer umbrella per se.
