Generates a web-based representation of individual OB issues
and amendment search across OB issues.

= Authoring

== OB issues

Place each OB issue under `issues/{{ OB No. }}/` directory.

Each OB issue should contain the following files:

* `meta.yaml` — Information about OB issue: number, date, authors, etc.
* `general.yaml` — General information from the OB issue.
* `amendments.yaml` — The amendments part from the OB issue.
* `nnp_communications/{{ filename }}` — Texts of communications mentioned
  in the General Information part under E.164 section.
  The filename is referenced under `_contents` key for each communication
  in `general.yaml`.

See issue 1173 in link:https://github.com/riboseinc/itu-ob-data/[itu-ob-data]
(work in progress).

== NNP data

NNP-related data, and changes to that data, is not described formally
in OB issues. Place NNP data in XML, obtained from NNP team, under `nnp/`.

= Implementation details

The following plugins enable the site to function:

* Issue data reader — processes OB issue YAML, AsciiDoc and NNP XML as needed,
  and populates ``site.data`` with structured information
  about OB issues and changes in telecommunications landscape covered by ITU
* Issue page generator — creates a page for each OB issue using ``site.data``
* Amendment search index generator — to facilitate client-side search
  of changes in ITU, creates JSON indexes from OB issue data and from NNP data

== Vocabulary

* ITU OB: ITU Operational Bulletin.

* Message: a piece of information disseminated via ITU OB.
  Maps to a section within an OB issue.

  Usually a message is connected to an ITU recommendation.

  A message may be an amendment, or otherwise be a notice of general kind.

  * Amendment: an update to a previous ITU publication
    (such as a List position annexed to a previous OB issue,
    or an “external publication” such as the List V).

    Always specifies the target being amended and the _changeset_.
  
    * Amendment target: references the original publication being amended.
      Specifies _type_ (classifying original publication)
      and _ref_ (identifying specific issue of said publication).
    
* External publication: ITU publication not annexed to a previous OB issue.

* List: a dataset maintained by ITU in connection with a certain Recommendation.

  * List position: a snapshot of that dataset deemed as valid at given point in time.
+
From time to time (could be every few years), a new snapshot of a List is created.
+
This happens around planned publication date of next OB issue, and that issue
is then published with dataset snapshot (List position) annexed to it.
+
Subsequent OB issues may disseminate amendments to that dataset,
until a new snapshot is published.

=== Commonly present general notice types

* Telephone Service
* Service Restrictions
* Call-back and alternative calling procedures
